spring:
  datasource:
    # Using file-based H2 database for persistence
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      
       
    
  
    
