spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hib
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Fayaz78677@
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    